### ISSUE TITLE
Delete DynamicArray

### ISSUE THREAD

**Issue by andrelugomes** [rasmus4200/algorithms101#6]
Hello,

While following this example: https://www.udemy.com/course/data-structures-and-algorithms-bootcamp/learn/lecture/16887116#questions

The array always hold tha last index:

![image](https://user-images.githubusercontent.com/1247724/77021843-b277d580-6966-11ea-923b-7faed557828f.png)
 after delete `array.delete(1)`

![image](https://user-images.githubusercontent.com/1247724/77021901-d89d7580-6966-11ea-95b9-b86eac56ca7a.png)

To solve this, a simple `else

```
public void delete(int index) {
        // Copy down
        for (int j = index; j < size - 1; j++) {
            data[j] = data[j + 1];
        }

        // Clear if last element in array
        if (index == size) {
            data[index] = null;
        }else {
            //Clear last value index
            data[size - 1] = null;
        }
        size--;
    }
```

**Comment by jrasmusson** [comment]
Hi André! Thank you so much for commenting on this code.

I think the solution I have works as is.

`    public void delete(int index) {
        // Copy down
        for (int j = index; j < size - 1; j++) {
            data[j] = data[j + 1];
        }
        size--;

        // Clear if last element in array
        if (index == size) {
            data[index] = null;
        }
    }
`
Because I decrement `size--` before doing the check, I can delete the last element OK.

So if we look at this example.

0   1   2       size = 3
a   b  c

delete(2)
copy down

0   1   2       size = 3
b   c   c       index = 2

We now have an extra c at index = 2 that we want to delete.
If we decrement the size--

0   1   2       size = 2
b   c   c       index = 2

We can delete the last element if the index == the new size or our array.

`if (index == size) {   // 2 = 2
            data[index] = null;
  }`

0   1   2           size = 2
b   c   null       index = 2

Does this make sense? I may have missed something, but I think it works.

If it doesn't, can your write a unit test that shows me where the bug is? I can then try to fix.

Thank you so much for raising this question and asking. 

Cheers - Jonathan

**Comment by andrelugomes** [comment]
Hi Jonathan, tanks fos answer :)

I'm actually writing unit tests for the exercises

https://github.com/andrelugomes/data-structures-and-algorithms/blob/master/java/src/test/java/datastructures/DynamicArrayTest.java

I'll follow your suggestion and check by the tests.

**Comment by andrelugomes** [comment]
It doesn't work.

```
public void delete(int index) {
        // Copy down
        for (int j = index; j < size - 1; j++) {
            data[j] = data[j + 1];
        }
        size--;

        // Clear if last element in array
        if (index == size) {
            data[index] = null;
        }
    }
```

![image](https://user-images.githubusercontent.com/1247724/77234734-97d47500-6b8f-11ea-8ab4-8727daf0d666.png)


By my sugestion:

![image](https://user-images.githubusercontent.com/1247724/77234811-01548380-6b90-11ea-8063-10392166d578.png)

**Comment by jrasmusson** [comment]
Which assertion in your unit test is failing?

**Comment by andrelugomes** [comment]
The unit tests are passing. But the final array still holding dirty data in last index.

**Comment by jrasmusson** [comment]
Apologies :) I understand now. Bad unit test on my part.
Yes you are correct! And you solution works! Thank you. 

I am going to tweak it a bit and add some comments. 

Thanks again for pointing this out. You are really getting this stuff!

Cheers - Jonathan

**Comment by jrasmusson** [comment]
Note: I gave you credit for finding the but on the page that explains what the bug is. Let me know if you if that is OK.

Cheers - Jonathan

**Comment by andrelugomes** [comment]
Hi @jrasmusson 

I'm pretty happy to discuss with you that solution. 
Congratulations! The course is awesome.
